"use client";

import { useEffect } from "react";
import { FormProvider, useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";

import { useUserSettings } from "@/queries/user-settings/useUserSettings";
import { FormCheckbox } from "@/components/inputs/FormCheckbox";
import { aiFillFieldsSchema, type AiFillFields } from "./aiFillFields.schema";
import { useUpdateAiFillSettings } from "@/queries/user-settings/useUpdateAiFillSettings";
import { ArrowButton } from "@/components/ArrowButton";

export const AIFillSettingsForm = () => {
  const { data: userSettings } = useUserSettings();
  const aiFillFields = userSettings?.ai_fill_fields as AiFillFields | undefined;
  const { mutate: updateAiFillSettings, isPending } = useUpdateAiFillSettings();

  const methods = useForm<AiFillFields>({
    resolver: zodResolver(aiFillFieldsSchema),
    defaultValues: {
      antonyms: false,
      synonyms: false,
      description: false,
      example: false,
      part_of_speech: false,
      translation: false,
    },
  });

  const {
    handleSubmit,
    formState: { isDirty },
  } = methods;

  useEffect(() => {
    if (aiFillFields) {
      methods.reset(aiFillFields);
    }
  }, [aiFillFields]);

  const onSubmit = (data: AiFillFields) => {
    updateAiFillSettings(data, {
      onSuccess: () => methods.reset(data),
    });
  };

  return (
    <FormProvider {...methods}>
      <form
        className="flex h-full flex-col justify-between"
        onSubmit={handleSubmit(onSubmit)}
      >
        <div className="space-y-5">
          <p className="text-sm text-muted-foreground">
            Choose which fields should be automatically generated by AI when
            creating a word. Unchecked fields will be left empty.
          </p>

          <div className="space-y-4">
            <FormCheckbox
              name="translation"
              label="Translation"
              description="Automatically generate the translation."
            />

            <FormCheckbox
              name="synonyms"
              label="Synonyms"
              description="Generate related words with similar meanings."
            />

            <FormCheckbox
              name="antonyms"
              label="Antonyms"
              description="Generate words with opposite meanings."
            />

            <FormCheckbox
              name="part_of_speech"
              label="Word Type"
              description="Detect the part of speech automatically."
            />

            <FormCheckbox
              name="example"
              label="Example"
              description="Generate an example sentence."
            />

            <FormCheckbox
              name="description"
              label="Description"
              description="Generate a short explanation of the word."
            />
          </div>
        </div>

        <div className="flex justify-end">
          <ArrowButton type="submit" disabled={!isDirty} isLoading={isPending}>
            {isPending ? "Saving..." : "Save"}
          </ArrowButton>
        </div>
      </form>
    </FormProvider>
  );
};

export default AIFillSettingsForm;
