import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@wrksz/themes/next";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "@/components/ui/sonner";
import { QueryProviders } from "@/components/providers/query-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="h-full antialiased">
      <body className="flex h-full flex-col overflow-hidden">
        <QueryProviders>
          <ThemeProvider>
            <TooltipProvider>{children}</TooltipProvider>
            <Toaster position="bottom-center" />
          </ThemeProvider>
        </QueryProviders>
      </body>
    </html>
  );
}
