import {
  PlusCircle,
  FolderPlus,
  MessagesSquare,
  Plus,
  Search,
  ChevronRight,
  ChevronLeft,
  ChevronDownIcon,
  FolderDown,
  Clock,
  Gamepad2,
  ChartNoAxesColumn,
  Trash,
  MoreHorizontal,
  MoveRight,
  Calendar,
  AudioLines,
  SquarePen,
  Copy,
  FolderOutput,
  UserRoundPlus,
  UserRoundKey,
  Mail,
  CircleUserRound,
  Lock,
  Eye,
  EyeOff,
  Key,
  RefreshCcw,
  MailCheck,
} from "lucide-react";

export const AppIcons = {
  FeedIcon: MessagesSquare,
  ClockIcon: Clock,
  NewCategoryIcon: FolderPlus,
  NewWordIcon: PlusCircle,
  ImportIcon: FolderDown,
  PracticeIcon: Gamepad2,
  DashboardIcon: ChartNoAxesColumn,
  TrashIcon: Trash,

  PlusIcon: Plus,
  SearchIcon: Search,
  ChevronRightIcon: ChevronRight,
  ChevronDownIcon,
  MoreHorizontalIcon: MoreHorizontal,
  ChevronLeftIcon: ChevronLeft,

  MoveRightIcon: MoveRight,
  CalendarIcon: Calendar,
  AudioIcon: AudioLines,

  EditIcon: SquarePen,
  CopyIcon: Copy,
  MoveIcon: FolderOutput,

  SignupIcon: UserRoundPlus,
  LoginIcon: UserRoundKey,
  KeyIcon: Key,
  RefreshCcwIcon: RefreshCcw,
  MailIcon: Mail,
  CircleUserRoundIcon: CircleUserRound,
  LockIcon: Lock,
  EyeIcon: Eye,
  EyeOffIcon: EyeOff,
  MailCheckIcon: MailCheck,
};
